export interface Plant {
	id: string;
	name: string;
	scientific_name?: string;
	common_name: Array<string>;
	plant_family?: string;
	plant_type?: Array<string>;
	height_min_ft?: number;
	height_max_ft?: number;
	growth_rate?: string;
	lifespan?: Array<string>;
	flowering_months?: Array<string>;
	sun_and_shade?: Array<string>;
	soil_moisture?: Array<string>;
	monarchs?: boolean;
	native_bees?: boolean;
	honey_bees?: boolean;
	bombus?: boolean;
	butterflies?: boolean;
	moths?: boolean;
	hummingbirds?: boolean;
	beetles_wasps_flies?: boolean;
	bats?: boolean;
	nesting_and_structure_bees?: boolean;
	larval_host_monarch?: boolean;
	larval_host_butterfly?: boolean;
	larval_host_moth?: boolean;
	image_url?: string;
}
